### ISSUE TITLE
help to flash i9100

### ISSUE THREAD

**Issue by orz007** [Benjamin-Dobell/Heimdall#331]
No ERROR SHOW ME
======================
Copyright (c) 2010-2014 Benjamin Dobell, Glass Echidna
http://www.glassechidna.com.au/

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://www.glassechidna.com.au/donate/

Initialising connection...
Detecting device...
Claiming interface...
Setting up interface...

Beginning session...
Releasing device interface...
======================================
usb-log-debug 

http://pastebin.com/WhCvfz1N

**Comment by Benjamin-Dobell** [comment]
Sorry, I have no idea what this issue is about.

Looking at the pastebin I see a successful attempt to print-pit.

Due to the lack of information I'm closing this. If you've encountered a bug/issue, then please create a new issue and be descriptive about your system, what you're trying to achieve, the steps you've taken, the expected result, and the result that you did achieve.
